workflow fixes

diff --git a/.github/workflows/plots.yml b/.github/workflows/plots.yml
--- a/.github/workflows/plots.yml
+++ b/.github/workflows/plots.yml
@@ -15,12 +15,16 @@ jobs:
         with:
           persist-credentials: true
 
+
       - name: Set up GitHub credentials
         run: |
           git config --global --add safe.directory "$GITHUB_WORKSPACE"
           git config --global user.name "github-actions[bot]"
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
           git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
+          git fetch origin ${{ github.ref_name }} || { echo "git fetch failed"; exit 1; }
+          git checkout ${{ github.ref_name }} || { echo "git checkout failed"; exit 1; }
+          git pull --rebase origin ${{ github.ref_name }} || { echo "git pull failed"; exit 1; }
 
       - name: Install Python and dependencies
         run: |
@@ -28,7 +32,6 @@ jobs:
           sudo apt-get install -y python3 python3-pip
           python3 -m pip install --upgrade pip
           pip3 install --break-system-packages pandas matplotlib
-          git pull --rebase || { echo "git pull failed"; exit 1; }
 
       - name: Generate plots
         run: python3 ./cmd/plot.py
